export { AltudeVault } from './vault.js'
export type { CreateWalletOptions } from './wallet/index.js'
export type { CreateApiKeyOptions, CreatedApiKey } from './wallet/apikeys.js'
export type { AuditLogEntry, AuditEventType } from './audit/index.js'
export type { PolicyResult } from './policy/index.js'
export { NodeVaultStorage, BrowserVaultStorage } from './storage/index.js'
export type { VaultStorage } from './storage/index.js'
export { evaluatePolicy, evaluatePolicies } from './policy/index.js'
export { encryptWithPassphrase, decryptWithPassphrase, encryptWithToken, decryptWithToken } from './crypto/index.js'
export { backupVault, restoreVault } from './backup/index.js'
